name: Builds a container when needed and publishes it to registry
on:
  push:
    paths:
    - 'META6.json'
    - '.github/workflows/dockerize.yml'
    
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checks out files
      uses: actions/checkout@master
    - name: Downloads image
      run: |
        wget https://raw.githubusercontent.com/JJ/raku-container-action/master/raku-install.Dockerfile
    - name: Adds preinstall and startup stuff
      run: |
        sed -i 's/#Preinstall/#Preinstall\nRUN apk update \&\& apk upgrade \&\& apk add gcc libc-dev sqlite-libs redis \&\& zef install --/test "NativeLibs:ver<0.0.7>:auth<github:salortiz>"/' raku-install.Dockerfile
        sed -i 's/raku -v \&\&/redis-server \/etc\/redis.conf \&/' raku-install.Dockerfile
        cat raku-install.Dockerfile
    - name: Builds and publishes to GPR
      uses: JJ/gpr-docker-publish@master
      with:
        IMAGE_NAME: 'rakurecipes'
        TAG: 'latest'
        DOCKERFILE_PATH: 'raku-install.Dockerfile'
        BUILD_CONTEXT: '.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
