name: Tests utility module
on: [push,pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests this
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Runs tests
      id: tests
      with:
        GH_REGISTRY_TOKEN: {{secrets.GH_REGISTRY_TOKEN}}
      run: |
        docker login docker.pkg.github.com -u JJ -p $GH_REGISTRY_TOKEN
        docker run -t -v $PWD:/test docker.pkg.github.com/jj/perl6-recipes-apress/rakurecipes:latest
